### ISSUE TITLE
Error on launch - Split-Path : Cannot bind argument to parameter 'Path' because it is null

### ISSUE THREAD

**Issue by nacabuta** [manoj2994/Network-Check-Portal-#1]
Hello

This looks cool by the way but besides some hardcoded paths and spelling errors I recieve this error on launch.

`Split-Path : Cannot bind argument to parameter 'Path' because it is null.`
`At line:1 char:35`
`+ $PSScriptRoot =  Split-Path -Path $psISE.CurrentFile.FullPath`
`+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException`
`    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.SplitPathCommand`

PS
OS is Win2019

**Comment by manoj2994** [comment]
HI 
Thanks , As its is coded in ISE ,the $PSScriptroot wont work

If using ISE use:

$psISE.CurrentFile.FullPath

When ISE is launched, $psISE is created and can be used to determine the current path of the ISE instance. This was introduced in version 3.0.

If you are using Powershell Console use the default $Psscriptroot instead of $psISE.CurrentFile.FullPath

**Comment by manoj2994** [comment]
HI nacabuta

Have updated the Main page and made some changes now you can run the main.ps1 in powershell console alone,to start the dashboard

Cheers!!!!!
